# rh-mastery — Red Hat documentation PDF mirror + convert (RHEL 10)
# Build (on RHEL 10 or compatible, with network for pip during %%install):
#   ./packaging/rpm/build-rpm.sh
#
# Requires: git, python3-pip, rpm-build, gcc (some wheels may need a compiler;
#           prebuilt manylinux wheels usually suffice on x86_64/aarch64).

%global pkgname rh-mastery

# Vendored wheels ship ELF modules; skip separate debuginfo.
%global debug_package %{nil}

Name:           rh-mastery
Version:        0.1.0
Release:        1%{?dist}
Summary:        Mirror Red Hat product docs (PDF) and optional Markdown conversion

License:        Apache-2.0
URL:            https://github.com/
Source0:        %{pkgname}-%{version}.tar.gz

# Vendor tree contains arch-specific extension modules (PyMuPDF).
ExclusiveArch:  x86_64 aarch64

BuildRequires:  python3
BuildRequires:  python3-pip
BuildRequires:  systemd-rpm-macros

Requires:       python3
Requires:       systemd

# Optional: cron examples reference crond
Recommends:     cronie

%description
rh-mastery downloads Red Hat product documentation PDFs from docs.redhat.com,
tracks versions in rh_config.json, and can convert mirrored PDFs to Markdown
via the built-in convert subcommand (PDF only).

This package installs the application under %{_prefix}/lib/rh-mastery with
Python dependencies vendored under vendor/ (PyPI wheels at build time).
Configuration defaults live under %{_sysconfdir}/rh-mastery; run commands from
that directory or copy configs to your working directory.

%prep
%setup -q -n %{pkgname}-%{version}

%build
# Nothing to compile; Python deps are installed in %%install.
:

%install
install -d %{buildroot}%{_prefix}/lib/%{pkgname}/vendor
install -m0644 rh_mastery.py %{buildroot}%{_prefix}/lib/%{pkgname}/
install -m0755 rh-mastery %{buildroot}%{_prefix}/lib/%{pkgname}/

# Vendored site-packages (requires network during rpmbuild unless wheels are prefetched).
pip3 install \
    --no-cache-dir \
    --disable-pip-version-check \
    -r requirements.txt \
    -t %{buildroot}%{_prefix}/lib/%{pkgname}/vendor

# /usr/bin launcher — prepend vendor on PYTHONPATH before invoking real wrapper.
install -d %{buildroot}%{_bindir}
cat > %{buildroot}%{_bindir}/rh-mastery << 'LAUNCHER'
#!/usr/bin/bash
# Generated by rh-mastery.spec — do not edit; use drop-in or /etc/profile.d.
export PYTHONPATH="%{_prefix}/lib/rh-mastery/vendor${PYTHONPATH:+:$PYTHONPATH}"
exec "%{_prefix}/lib/rh-mastery/rh-mastery" "$@"
LAUNCHER
chmod 0755 %{buildroot}%{_bindir}/rh-mastery

# Config (noreplace)
install -d %{buildroot}%{_sysconfdir}/rh-mastery
install -m0644 rh_config.json %{buildroot}%{_sysconfdir}/rh-mastery/rh_config.json
install -m0644 rh_storage.json %{buildroot}%{_sysconfdir}/rh-mastery/rh_storage.json

# Point defaults at local state dir (matches container layout).
python3 << 'PY'
import json
from pathlib import Path

root = Path("%{buildroot}")
cfg_path = root / "etc/rh-mastery/rh_config.json"
with cfg_path.open() as f:
    cfg = json.load(f)
cfg.setdefault("settings", {})
cfg["settings"]["download_base"] = "/var/lib/rh-mastery/RHDocumentation"
with cfg_path.open("w") as f:
    json.dump(cfg, f, indent=4)

stor_path = root / "etc/rh-mastery/rh_storage.json"
with stor_path.open() as f:
    st = json.load(f)
st["mount_point"] = "/var/lib/rh-mastery"
st["sync_subdir"] = "RHDocumentation"
with stor_path.open("w") as f:
    json.dump(st, f, indent=4)
PY

# State directory (empty tree owned by package)
install -d %{buildroot}/var/lib/rh-mastery/RHDocumentation

# systemd
install -d %{buildroot}%{_unitdir}
install -m0644 packaging/rpm/systemd/rh-mastery-sync.service %{buildroot}%{_unitdir}/
install -m0644 packaging/rpm/systemd/rh-mastery-sync.timer %{buildroot}%{_unitdir}/

%post
# Seed state dir so systemd timer can run without manual copy.
if [ -f %{_sysconfdir}/rh-mastery/rh_config.json ] && [ ! -f /var/lib/rh-mastery/rh_config.json ]; then
  cp -a %{_sysconfdir}/rh-mastery/rh_config.json /var/lib/rh-mastery/rh_config.json
fi
if [ -f %{_sysconfdir}/rh-mastery/rh_storage.json ] && [ ! -f /var/lib/rh-mastery/rh_storage.json ]; then
  cp -a %{_sysconfdir}/rh-mastery/rh_storage.json /var/lib/rh-mastery/rh_storage.json
fi
%systemd_post rh-mastery-sync.service rh-mastery-sync.timer

%preun
%systemd_preun rh-mastery-sync.service rh-mastery-sync.timer

%postun
%systemd_postun_with_restart rh-mastery-sync.service rh-mastery-sync.timer

%files
%license LICENSE
%doc README.md
%doc packaging/rpm/README.md
%doc container/cron/rh-mastery.example
%{_bindir}/rh-mastery
%{_prefix}/lib/%{pkgname}/rh_mastery.py
%{_prefix}/lib/%{pkgname}/rh-mastery
%{_prefix}/lib/%{pkgname}/vendor/
%config(noreplace) %{_sysconfdir}/rh-mastery/rh_config.json
%config(noreplace) %{_sysconfdir}/rh-mastery/rh_storage.json
%dir %attr(0755,root,root) /var/lib/rh-mastery
%dir %attr(0755,root,root) /var/lib/rh-mastery/RHDocumentation
%{_unitdir}/rh-mastery-sync.service
%{_unitdir}/rh-mastery-sync.timer

%changelog
* Fri Apr 03 2026 rh-mastery packaging <rh-mastery@localhost> - 0.1.0-1
- Initial RPM for RHEL 10 (vendored Python deps, systemd units)
